export interface TemplateDesign {
  id: string;
  name: string;
  category: string;
  lines: { text: string; font: string; size: number; color: string; weight: string; style?: string }[];
}

export const TEMPLATE_CATEGORIES = [
  "All", "Bold & Classic", "Street Style", "Vintage", "Motivational",
  "Fun & Quirky", "Sports", "Nature", "Music", "Minimal"
];

export const TEMPLATE_DESIGNS: TemplateDesign[] = [
  { id:"bc1", name:"Est. 2024", category:"Bold & Classic", lines:[{ text:"EST.", font:"Impact", size:28, color:"#ffffff", weight:"bold" },{ text:"2024", font:"Impact", size:56, color:"#ffffff", weight:"bold" }] },
  { id:"bc2", name:"Original Design", category:"Bold & Classic", lines:[{ text:"ORIGINAL", font:"Impact", size:36, color:"#FFD700", weight:"bold" },{ text:"DESIGN", font:"Impact", size:36, color:"#ffffff", weight:"bold" }] },
  { id:"bc3", name:"Limited Edition", category:"Bold & Classic", lines:[{ text:"LIMITED", font:"Impact", size:38, color:"#ffffff", weight:"bold" },{ text:"EDITION", font:"Impact", size:38, color:"#FF4444", weight:"bold" }] },
  { id:"bc4", name:"100% Original", category:"Bold & Classic", lines:[{ text:"100%", font:"Impact", size:48, color:"#FFD700", weight:"bold" },{ text:"ORIGINAL", font:"Impact", size:32, color:"#ffffff", weight:"bold" }] },
  { id:"bc5", name:"Made to Order", category:"Bold & Classic", lines:[{ text:"MADE TO", font:"Arial", size:32, color:"#ffffff", weight:"bold" },{ text:"ORDER", font:"Arial", size:44, color:"#4dffb4", weight:"bold" }] },
  { id:"bc6", name:"Handmade", category:"Bold & Classic", lines:[{ text:"HANDMADE", font:"Georgia", size:34, color:"#ffffff", weight:"bold" },{ text:"WITH \u2665", font:"Georgia", size:28, color:"#FF6B8A", weight:"bold" }] },
  { id:"bc7", name:"Custom Print", category:"Bold & Classic", lines:[{ text:"CUSTOM", font:"Verdana", size:36, color:"#c3b1e1", weight:"bold" },{ text:"PRINT", font:"Verdana", size:36, color:"#ffffff", weight:"bold" }] },
  { id:"bc8", name:"Classic 1985", category:"Bold & Classic", lines:[{ text:"CLASSIC", font:"Impact", size:40, color:"#ffffff", weight:"bold" },{ text:"1985", font:"Impact", size:52, color:"#FFD700", weight:"bold" }] },
  { id:"bc9", name:"Premium Quality", category:"Bold & Classic", lines:[{ text:"PREMIUM", font:"Impact", size:36, color:"#FFD700", weight:"bold" },{ text:"QUALITY", font:"Impact", size:36, color:"#ffffff", weight:"bold" }] },
  { id:"bc10", name:"Number One", category:"Bold & Classic", lines:[{ text:"#1", font:"Impact", size:72, color:"#FFD700", weight:"bold" },{ text:"ALWAYS", font:"Impact", size:28, color:"#ffffff", weight:"bold" }] },
  { id:"bc11", name:"The Original", category:"Bold & Classic", lines:[{ text:"THE", font:"Arial", size:24, color:"#aaaaaa", weight:"normal" },{ text:"ORIGINAL", font:"Impact", size:44, color:"#ffffff", weight:"bold" }] },
  { id:"bc12", name:"Born Classic", category:"Bold & Classic", lines:[{ text:"BORN", font:"Impact", size:44, color:"#ffffff", weight:"bold" },{ text:"CLASSIC", font:"Impact", size:36, color:"#FFD700", weight:"bold" }] },
  { id:"ss1", name:"Street Style", category:"Street Style", lines:[{ text:"STREET", font:"Impact", size:40, color:"#4dffb4", weight:"bold" },{ text:"STYLE", font:"Impact", size:40, color:"#ffffff", weight:"bold" }] },
  { id:"ss2", name:"Urban Legend", category:"Street Style", lines:[{ text:"URBAN", font:"Verdana", size:36, color:"#ff6b6b", weight:"bold" },{ text:"LEGEND", font:"Verdana", size:36, color:"#ffffff", weight:"bold" }] },
  { id:"ss3", name:"Fresh Drip", category:"Street Style", lines:[{ text:"FRESH", font:"Impact", size:44, color:"#FFD700", weight:"bold" },{ text:"DRIP", font:"Impact", size:44, color:"#4dffb4", weight:"bold" }] },
  { id:"ss4", name:"Hustle Hard", category:"Street Style", lines:[{ text:"HUSTLE", font:"Impact", size:38, color:"#ffffff", weight:"bold" },{ text:"HARD", font:"Impact", size:52, color:"#FF4444", weight:"bold" }] },
  { id:"ss5", name:"No Days Off", category:"Street Style", lines:[{ text:"NO DAYS", font:"Impact", size:38, color:"#ffffff", weight:"bold" },{ text:"OFF", font:"Impact", size:52, color:"#4dffb4", weight:"bold" }] },
  { id:"ss6", name:"Stay Woke", category:"Street Style", lines:[{ text:"STAY", font:"Verdana", size:32, color:"#aaaaaa", weight:"bold" },{ text:"WOKE", font:"Impact", size:48, color:"#FFD700", weight:"bold" }] },
  { id:"ss7", name:"Grind Mode", category:"Street Style", lines:[{ text:"GRIND", font:"Impact", size:44, color:"#FF4444", weight:"bold" },{ text:"MODE", font:"Impact", size:44, color:"#ffffff", weight:"bold" }] },
  { id:"ss8", name:"Vibe Check", category:"Street Style", lines:[{ text:"VIBE", font:"Impact", size:48, color:"#c3b1e1", weight:"bold" },{ text:"CHECK", font:"Verdana", size:28, color:"#4dffb4", weight:"bold" }] },
  { id:"ss9", name:"Real Ones", category:"Street Style", lines:[{ text:"REAL", font:"Impact", size:44, color:"#ffffff", weight:"bold" },{ text:"ONES", font:"Impact", size:44, color:"#FFD700", weight:"bold" }] },
  { id:"ss10", name:"No Cap", category:"Street Style", lines:[{ text:"NO", font:"Impact", size:44, color:"#ff6b6b", weight:"bold" },{ text:"CAP", font:"Impact", size:64, color:"#ffffff", weight:"bold" }] },
  { id:"ss11", name:"Lowkey Legend", category:"Street Style", lines:[{ text:"lowkey", font:"Verdana", size:28, color:"#aaaaaa", weight:"normal", style:"italic" },{ text:"LEGEND", font:"Impact", size:44, color:"#4dffb4", weight:"bold" }] },
  { id:"ss12", name:"Drip or Drown", category:"Street Style", lines:[{ text:"DRIP", font:"Impact", size:44, color:"#4dffb4", weight:"bold" },{ text:"OR DROWN", font:"Impact", size:32, color:"#ffffff", weight:"bold" }] },
  { id:"v1", name:"Est. Since 1990", category:"Vintage", lines:[{ text:"EST. SINCE", font:"Georgia", size:22, color:"#fad7a0", weight:"normal" },{ text:"1990", font:"Georgia", size:52, color:"#fad7a0", weight:"bold" }] },
  { id:"v2", name:"Retro Vibes", category:"Vintage", lines:[{ text:"RETRO", font:"Georgia", size:44, color:"#fad7a0", weight:"bold" },{ text:"VIBES", font:"Georgia", size:44, color:"#FF6B8A", weight:"bold" }] },
  { id:"v3", name:"Old School", category:"Vintage", lines:[{ text:"OLD", font:"Courier New", size:36, color:"#fad7a0", weight:"bold" },{ text:"SCHOOL", font:"Courier New", size:36, color:"#ffffff", weight:"bold" }] },
  { id:"v4", name:"Since 1969", category:"Vintage", lines:[{ text:"SINCE", font:"Georgia", size:24, color:"#aaaaaa", weight:"normal" },{ text:"1969", font:"Georgia", size:56, color:"#fad7a0", weight:"bold" }] },
  { id:"v5", name:"Aged to Perfection", category:"Vintage", lines:[{ text:"AGED TO", font:"Georgia", size:28, color:"#fad7a0", weight:"bold" },{ text:"PERFECTION", font:"Georgia", size:26, color:"#ffffff", weight:"bold" }] },
  { id:"v6", name:"Classic Rock", category:"Vintage", lines:[{ text:"CLASSIC", font:"Impact", size:36, color:"#fad7a0", weight:"bold" },{ text:"ROCK", font:"Impact", size:52, color:"#FF4444", weight:"bold" }] },
  { id:"v7", name:"Varsity 77", category:"Vintage", lines:[{ text:"VARSITY", font:"Impact", size:36, color:"#ffffff", weight:"bold" },{ text:"'77", font:"Impact", size:56, color:"#FFD700", weight:"bold" }] },
  { id:"v8", name:"Made in the 80s", category:"Vintage", lines:[{ text:"MADE IN", font:"Courier New", size:22, color:"#aaaaaa", weight:"normal" },{ text:"THE 80s", font:"Impact", size:44, color:"#fad7a0", weight:"bold" }] },
  { id:"v9", name:"Timeless", category:"Vintage", lines:[{ text:"TIMELESS", font:"Georgia", size:36, color:"#fad7a0", weight:"bold" }] },
  { id:"v10", name:"Forever Classic", category:"Vintage", lines:[{ text:"FOREVER", font:"Georgia", size:32, color:"#fad7a0", weight:"bold" },{ text:"CLASSIC", font:"Georgia", size:32, color:"#FF6B8A", weight:"bold" }] },
  { id:"m1", name:"Dream Big", category:"Motivational", lines:[{ text:"DREAM", font:"Impact", size:44, color:"#c3b1e1", weight:"bold" },{ text:"BIG", font:"Impact", size:64, color:"#ffffff", weight:"bold" }] },
  { id:"m2", name:"Never Give Up", category:"Motivational", lines:[{ text:"NEVER", font:"Impact", size:38, color:"#FF4444", weight:"bold" },{ text:"GIVE UP", font:"Impact", size:38, color:"#ffffff", weight:"bold" }] },
  { id:"m3", name:"Work Hard", category:"Motivational", lines:[{ text:"WORK", font:"Impact", size:44, color:"#4dffb4", weight:"bold" },{ text:"HARD", font:"Impact", size:44, color:"#ffffff", weight:"bold" }] },
  { id:"m4", name:"Stay Focused", category:"Motivational", lines:[{ text:"STAY", font:"Verdana", size:28, color:"#aaaaaa", weight:"bold" },{ text:"FOCUSED", font:"Impact", size:44, color:"#4dffb4", weight:"bold" }] },
  { id:"m5", name:"Chase Dreams", category:"Motivational", lines:[{ text:"CHASE", font:"Impact", size:40, color:"#FFD700", weight:"bold" },{ text:"YOUR DREAMS", font:"Impact", size:28, color:"#ffffff", weight:"bold" }] },
  { id:"m6", name:"Rise & Grind", category:"Motivational", lines:[{ text:"RISE &", font:"Impact", size:38, color:"#FF4444", weight:"bold" },{ text:"GRIND", font:"Impact", size:48, color:"#ffffff", weight:"bold" }] },
  { id:"m7", name:"Be the Change", category:"Motivational", lines:[{ text:"BE THE", font:"Georgia", size:28, color:"#aaaaaa", weight:"normal" },{ text:"CHANGE", font:"Impact", size:44, color:"#4dffb4", weight:"bold" }] },
  { id:"m8", name:"Push Limits", category:"Motivational", lines:[{ text:"PUSH", font:"Impact", size:48, color:"#c3b1e1", weight:"bold" },{ text:"LIMITS", font:"Impact", size:40, color:"#ffffff", weight:"bold" }] },
  { id:"m9", name:"Make it Happen", category:"Motivational", lines:[{ text:"MAKE IT", font:"Impact", size:36, color:"#FFD700", weight:"bold" },{ text:"HAPPEN", font:"Impact", size:40, color:"#ffffff", weight:"bold" }] },
  { id:"m10", name:"Born to Win", category:"Motivational", lines:[{ text:"BORN", font:"Impact", size:44, color:"#ffffff", weight:"bold" },{ text:"TO WIN", font:"Impact", size:44, color:"#4dffb4", weight:"bold" }] },
  { id:"m11", name:"Level Up", category:"Motivational", lines:[{ text:"LEVEL", font:"Impact", size:40, color:"#FFD700", weight:"bold" },{ text:"UP", font:"Impact", size:48, color:"#ffffff", weight:"bold" }] },
  { id:"m12", name:"Unstoppable", category:"Motivational", lines:[{ text:"UN", font:"Impact", size:36, color:"#aaaaaa", weight:"bold" },{ text:"STOPPABLE", font:"Impact", size:36, color:"#FF4444", weight:"bold" }] },
  { id:"fq1", name:"Weekend Mode", category:"Fun & Quirky", lines:[{ text:"WEEKEND", font:"Impact", size:36, color:"#4dffb4", weight:"bold" },{ text:"MODE ON", font:"Impact", size:36, color:"#ffffff", weight:"bold" }] },
  { id:"fq2", name:"Nap Champion", category:"Fun & Quirky", lines:[{ text:"NAP", font:"Impact", size:52, color:"#c3b1e1", weight:"bold" },{ text:"CHAMPION", font:"Impact", size:32, color:"#ffffff", weight:"bold" }] },
  { id:"fq3", name:"Coffee Mode", category:"Fun & Quirky", lines:[{ text:"COFFEE", font:"Impact", size:36, color:"#fad7a0", weight:"bold" },{ text:"MODE ON", font:"Verdana", size:24, color:"#ffffff", weight:"bold" }] },
  { id:"fq4", name:"Professional Snacker", category:"Fun & Quirky", lines:[{ text:"PROFESSIONAL", font:"Verdana", size:18, color:"#aaaaaa", weight:"normal" },{ text:"SNACKER", font:"Impact", size:40, color:"#FFD700", weight:"bold" }] },
  { id:"fq5", name:"404 Sleep Not Found", category:"Fun & Quirky", lines:[{ text:"404", font:"Courier New", size:44, color:"#4dffb4", weight:"bold" },{ text:"SLEEP NOT FOUND", font:"Courier New", size:18, color:"#ffffff", weight:"normal" }] },
  { id:"fq6", name:"Powered by Coffee", category:"Fun & Quirky", lines:[{ text:"POWERED", font:"Impact", size:34, color:"#ffffff", weight:"bold" },{ text:"BY COFFEE", font:"Impact", size:34, color:"#fad7a0", weight:"bold" }] },
  { id:"fq7", name:"Error 404", category:"Fun & Quirky", lines:[{ text:"ERROR", font:"Courier New", size:32, color:"#FF4444", weight:"bold" },{ text:"404", font:"Courier New", size:52, color:"#ffffff", weight:"bold" }] },
  { id:"fq8", name:"I Run on Chaos", category:"Fun & Quirky", lines:[{ text:"I RUN ON", font:"Verdana", size:24, color:"#aaaaaa", weight:"bold" },{ text:"CHAOS", font:"Impact", size:48, color:"#FF6B8A", weight:"bold" }] },
  { id:"fq9", name:"Ctrl Z My Life", category:"Fun & Quirky", lines:[{ text:"CTRL + Z", font:"Courier New", size:36, color:"#4dffb4", weight:"bold" },{ text:"MY LIFE", font:"Courier New", size:28, color:"#ffffff", weight:"normal" }] },
  { id:"fq10", name:"Debug Mode", category:"Fun & Quirky", lines:[{ text:"DEBUG", font:"Courier New", size:40, color:"#4dffb4", weight:"bold" },{ text:"MODE ON", font:"Courier New", size:28, color:"#ffffff", weight:"normal" }] },
  { id:"fq11", name:"Loading...", category:"Fun & Quirky", lines:[{ text:"LOADING", font:"Courier New", size:36, color:"#c3b1e1", weight:"bold" },{ text:"Please wait...", font:"Courier New", size:20, color:"#aaaaaa", weight:"normal" }] },
  { id:"fq12", name:"Sleep Eat Repeat", category:"Fun & Quirky", lines:[{ text:"SLEEP.", font:"Impact", size:36, color:"#c3b1e1", weight:"bold" },{ text:"EAT. REPEAT.", font:"Impact", size:28, color:"#ffffff", weight:"bold" }] },
  { id:"sp1", name:"No Pain No Gain", category:"Sports", lines:[{ text:"NO PAIN", font:"Impact", size:36, color:"#FF4444", weight:"bold" },{ text:"NO GAIN", font:"Impact", size:36, color:"#ffffff", weight:"bold" }] },
  { id:"sp2", name:"Beast Mode", category:"Sports", lines:[{ text:"BEAST", font:"Impact", size:44, color:"#FF4444", weight:"bold" },{ text:"MODE", font:"Impact", size:44, color:"#ffffff", weight:"bold" }] },
  { id:"sp3", name:"Train Hard", category:"Sports", lines:[{ text:"TRAIN", font:"Impact", size:44, color:"#4dffb4", weight:"bold" },{ text:"HARD", font:"Impact", size:44, color:"#ffffff", weight:"bold" }] },
  { id:"sp4", name:"Champions", category:"Sports", lines:[{ text:"BORN TO BE", font:"Verdana", size:20, color:"#aaaaaa", weight:"normal" },{ text:"CHAMPIONS", font:"Impact", size:36, color:"#FFD700", weight:"bold" }] },
  { id:"sp5", name:"Gym Life", category:"Sports", lines:[{ text:"GYM", font:"Impact", size:52, color:"#FF4444", weight:"bold" },{ text:"LIFE", font:"Impact", size:52, color:"#ffffff", weight:"bold" }] },
  { id:"sp6", name:"Just Run", category:"Sports", lines:[{ text:"JUST", font:"Impact", size:36, color:"#aaaaaa", weight:"bold" },{ text:"RUN", font:"Impact", size:64, color:"#FF4444", weight:"bold" }] },
  { id:"sp7", name:"Eat Sleep Repeat", category:"Sports", lines:[{ text:"EAT. SLEEP.", font:"Impact", size:28, color:"#aaaaaa", weight:"bold" },{ text:"REPEAT.", font:"Impact", size:44, color:"#4dffb4", weight:"bold" }] },
  { id:"sp8", name:"Winner Takes All", category:"Sports", lines:[{ text:"WINNER", font:"Impact", size:38, color:"#FFD700", weight:"bold" },{ text:"TAKES ALL", font:"Impact", size:32, color:"#ffffff", weight:"bold" }] },
  { id:"sp9", name:"Sweat Every Day", category:"Sports", lines:[{ text:"SWEAT", font:"Impact", size:40, color:"#ffffff", weight:"bold" },{ text:"EVERY DAY", font:"Impact", size:32, color:"#4dffb4", weight:"bold" }] },
  { id:"sp10", name:"All Day", category:"Sports", lines:[{ text:"ALL", font:"Impact", size:52, color:"#ffffff", weight:"bold" },{ text:"DAY", font:"Impact", size:52, color:"#4dffb4", weight:"bold" }] },
  { id:"n1", name:"Into the Wild", category:"Nature", lines:[{ text:"INTO THE", font:"Georgia", size:26, color:"#aaaaaa", weight:"normal" },{ text:"WILD", font:"Impact", size:52, color:"#4dffb4", weight:"bold" }] },
  { id:"n2", name:"Adventure Awaits", category:"Nature", lines:[{ text:"ADVENTURE", font:"Impact", size:32, color:"#4dffb4", weight:"bold" },{ text:"AWAITS", font:"Impact", size:32, color:"#ffffff", weight:"bold" }] },
  { id:"n3", name:"Wild & Free", category:"Nature", lines:[{ text:"WILD &", font:"Georgia", size:36, color:"#4dffb4", weight:"bold" },{ text:"FREE", font:"Georgia", size:52, color:"#ffffff", weight:"bold" }] },
  { id:"n4", name:"Born Wild", category:"Nature", lines:[{ text:"BORN", font:"Impact", size:44, color:"#ffffff", weight:"bold" },{ text:"WILD", font:"Impact", size:44, color:"#4dffb4", weight:"bold" }] },
  { id:"n5", name:"Go Outside", category:"Nature", lines:[{ text:"GO", font:"Impact", size:52, color:"#4dffb4", weight:"bold" },{ text:"OUTSIDE", font:"Impact", size:36, color:"#ffffff", weight:"bold" }] },
  { id:"n6", name:"Mountains Call", category:"Nature", lines:[{ text:"THE MOUNTAINS", font:"Georgia", size:20, color:"#aaaaaa", weight:"normal" },{ text:"ARE CALLING", font:"Georgia", size:22, color:"#ffffff", weight:"bold" }] },
  { id:"n7", name:"Earth First", category:"Nature", lines:[{ text:"EARTH", font:"Impact", size:44, color:"#4dffb4", weight:"bold" },{ text:"FIRST", font:"Impact", size:36, color:"#ffffff", weight:"bold" }] },
  { id:"n8", name:"Explore More", category:"Nature", lines:[{ text:"EXPLORE", font:"Impact", size:38, color:"#ffffff", weight:"bold" },{ text:"MORE", font:"Impact", size:48, color:"#4dffb4", weight:"bold" }] },
  { id:"n9", name:"Save the Planet", category:"Nature", lines:[{ text:"SAVE THE", font:"Verdana", size:24, color:"#4dffb4", weight:"bold" },{ text:"PLANET", font:"Verdana", size:32, color:"#ffffff", weight:"bold" }] },
  { id:"n10", name:"Nature Lover", category:"Nature", lines:[{ text:"NATURE", font:"Georgia", size:36, color:"#4dffb4", weight:"bold" },{ text:"LOVER", font:"Georgia", size:32, color:"#ffffff", weight:"bold" }] },
  { id:"mu1", name:"Rock & Roll", category:"Music", lines:[{ text:"ROCK &", font:"Impact", size:40, color:"#FF4444", weight:"bold" },{ text:"ROLL", font:"Impact", size:56, color:"#ffffff", weight:"bold" }] },
  { id:"mu2", name:"Music is Life", category:"Music", lines:[{ text:"MUSIC", font:"Impact", size:44, color:"#c3b1e1", weight:"bold" },{ text:"IS LIFE", font:"Impact", size:36, color:"#ffffff", weight:"bold" }] },
  { id:"mu3", name:"Good Vibes Only", category:"Music", lines:[{ text:"GOOD VIBES", font:"Impact", size:32, color:"#FFD700", weight:"bold" },{ text:"ONLY", font:"Impact", size:48, color:"#ffffff", weight:"bold" }] },
  { id:"mu4", name:"Turn it Up", category:"Music", lines:[{ text:"TURN IT", font:"Impact", size:36, color:"#ffffff", weight:"bold" },{ text:"UP", font:"Impact", size:52, color:"#FFD700", weight:"bold" }] },
  { id:"mu5", name:"Born to Rock", category:"Music", lines:[{ text:"BORN TO", font:"Impact", size:32, color:"#aaaaaa", weight:"bold" },{ text:"ROCK", font:"Impact", size:56, color:"#FF4444", weight:"bold" }] },
  { id:"mu6", name:"Bass Drop", category:"Music", lines:[{ text:"BASS", font:"Impact", size:52, color:"#c3b1e1", weight:"bold" },{ text:"DROP", font:"Impact", size:52, color:"#4dffb4", weight:"bold" }] },
  { id:"mu7", name:"World Off", category:"Music", lines:[{ text:"HEADPHONES ON", font:"Impact", size:24, color:"#c3b1e1", weight:"bold" },{ text:"WORLD OFF", font:"Impact", size:30, color:"#ffffff", weight:"bold" }] },
  { id:"mu8", name:"Play it Loud", category:"Music", lines:[{ text:"PLAY IT", font:"Impact", size:36, color:"#ffffff", weight:"bold" },{ text:"LOUD", font:"Impact", size:52, color:"#FF4444", weight:"bold" }] },
  { id:"mu9", name:"Feel the Beat", category:"Music", lines:[{ text:"FEEL THE", font:"Georgia", size:28, color:"#aaaaaa", weight:"normal" },{ text:"BEAT", font:"Impact", size:56, color:"#FFD700", weight:"bold" }] },
  { id:"mu10", name:"Live the Music", category:"Music", lines:[{ text:"LIVE THE", font:"Georgia", size:26, color:"#aaaaaa", weight:"normal" },{ text:"MUSIC", font:"Impact", size:44, color:"#c3b1e1", weight:"bold" }] },
  { id:"mn1", name:"Less is More", category:"Minimal", lines:[{ text:"less", font:"Georgia", size:32, color:"#aaaaaa", weight:"normal", style:"italic" },{ text:"is more.", font:"Georgia", size:32, color:"#ffffff", weight:"normal", style:"italic" }] },
  { id:"mn2", name:"Be Kind", category:"Minimal", lines:[{ text:"be", font:"Georgia", size:28, color:"#aaaaaa", weight:"normal", style:"italic" },{ text:"kind.", font:"Georgia", size:48, color:"#ffffff", weight:"normal", style:"italic" }] },
  { id:"mn3", name:"Breathe", category:"Minimal", lines:[{ text:"breathe.", font:"Georgia", size:40, color:"#c3b1e1", weight:"normal", style:"italic" }] },
  { id:"mn4", name:"Stay Calm", category:"Minimal", lines:[{ text:"stay", font:"Georgia", size:32, color:"#aaaaaa", weight:"normal" },{ text:"calm.", font:"Georgia", size:40, color:"#ffffff", weight:"normal", style:"italic" }] },
  { id:"mn5", name:"Just Be", category:"Minimal", lines:[{ text:"just", font:"Georgia", size:32, color:"#aaaaaa", weight:"normal", style:"italic" },{ text:"BE.", font:"Impact", size:52, color:"#ffffff", weight:"bold" }] },
  { id:"mn6", name:"Think Different", category:"Minimal", lines:[{ text:"think", font:"Georgia", size:28, color:"#aaaaaa", weight:"normal", style:"italic" },{ text:"different.", font:"Georgia", size:32, color:"#ffffff", weight:"normal", style:"italic" }] },
  { id:"mn7", name:"Do Good", category:"Minimal", lines:[{ text:"do", font:"Georgia", size:32, color:"#aaaaaa", weight:"normal" },{ text:"good.", font:"Georgia", size:48, color:"#4dffb4", weight:"normal", style:"italic" }] },
  { id:"mn8", name:"Stay True", category:"Minimal", lines:[{ text:"stay", font:"Georgia", size:32, color:"#aaaaaa", weight:"normal", style:"italic" },{ text:"true.", font:"Georgia", size:44, color:"#ffffff", weight:"normal", style:"italic" }] },
  { id:"mn9", name:"Love More", category:"Minimal", lines:[{ text:"love", font:"Georgia", size:40, color:"#FF6B8A", weight:"normal", style:"italic" },{ text:"more.", font:"Georgia", size:40, color:"#ffffff", weight:"normal", style:"italic" }] },
  { id:"mn10", name:"Simple", category:"Minimal", lines:[{ text:"simple.", font:"Georgia", size:44, color:"#ffffff", weight:"normal", style:"italic" }] },
];
